# -*- coding: utf-8 -*-
"""Hotel Review Sentiment Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cb0WnRhg5Xo_XYE8Wh-SxcKOcWxtbmKa

#Hotel Review Sentiment Analyzer
1.  Scenario:You want to predict whether hotel reviews are positive or negative.
2. Task: Use a Logistic Regression classifier to detect sentiment.
"""

from sklearn.metrics.pairwise import cosine_distances
from sklearn.linear_model import LogisticRegression
from sentence_transformers import SentenceTransformer

reviews = [
    "The room was clean and the staff were very friendly.",
    "Terrible experience. The hotel was dirty and noisy.",
    "Loved the breakfast and the view was amazing!",
    "Worst hotel ever. I will never come back.",
    "Comfortable beds and excellent service."]


labels = ["positive", "negative", "positive", "negative", "positive"]

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

X= model.encode(reviews)
y = labels

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)


y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

new_review = "The hotel had amazing service and very comfortable rooms."
embedding = model.encode([new_review])
prediction = clf.predict(embedding)[0]

print(f"Predicted Sentiment: {prediction}")