# -*- coding: utf-8 -*-
"""Product Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4JJmM9EtUa6fY9FoI51hAvvVd5Fb5AH

#QUESTION: 2 Product Recommendation System
1. Task:
Given product descriptions and customer browsing history, use embeddings + VectorDB to recommend top-5 similar products.
2. Key Skills:
Sentence embeddings, similarity search, ChromaDB integration.
3. Challenge:
Update the vector index in real-time when new products are added.
"""

!pip install langchain langchain-community sentence-transformers chromadb

from langchain_community.document_loaders import DirectoryLoader , TextLoader

products = [
    {
        "id": "1",
        "name": "Wireless Bluetooth Headphones",
        "description": """Experience exceptional sound quality with our Wireless Bluetooth Headphones.
         Designed for audiophiles and casual listeners alike, these over-ear headphones provide immersive audio with deep bass and crystal-clear highs.
         The noise-cancelling technology blocks out ambient sounds, allowing you to focus entirely on your music, podcasts, or calls.
         With 20-hour battery life, you can enjoy uninterrupted listening throughout the day, whether commuting, working, or traveling.
         Lightweight and ergonomically designed, these headphones ensure comfort during long listening sessions.
         The intuitive controls on the earcups let you adjust volume, skip tracks, and take calls seamlessly.
         Compatible with all Bluetooth-enabled devices, they also feature a fast-charging option that delivers hours of playtime in just a few minutes.
         Perfect for working professionals, students, and travelers, these headphones combine style, comfort, and premium sound in one sleek package."""
    },
    {
        "id": "2",
        "name": "Portable Bluetooth Speaker",
        "description": """Bring the party anywhere with our Portable Bluetooth Speaker.
         Compact yet powerful, this speaker delivers rich, full-range sound with deep bass and clear treble.
         Its waterproof design ensures you can use it at the pool, beach, or in the rain without worry.
         Featuring a 10-hour battery life, it lets you enjoy music all day on a single charge.
         The built-in microphone enables hands-free calling, making it a perfect companion for outdoor gatherings, picnics, or camping trips.
         Bluetooth connectivity ensures seamless pairing with your smartphone, tablet, or laptop. With its stylish, lightweight design, this speaker is easy to carry and fits in any bag or backpack.
         Ideal for music enthusiasts, travelers, or anyone who loves portable entertainment, it combines durability, convenience, and excellent sound quality in one device."""
    },
    {
        "id": "3",
        "name": "Smart Fitness Watch",
        "description": """Take charge of your health and fitness with our Smart Fitness Watch.
         Designed to track every step of your fitness journey, it monitors heart rate, sleep patterns, and workout performance with accuracy.
         The watch offers multiple sports modes, including running, cycling, swimming, and yoga, helping you optimize your exercise routine.
          With smartphone connectivity, it displays notifications, messages, and calls directly on your wrist.
          Its long-lasting battery ensures several days of continuous use, and the sleek, lightweight design makes it comfortable for all-day wear.
          Waterproof and durable, it withstands sweat and rain, making it perfect for any fitness activity.
          Whether you're a beginner or a professional athlete, this watch provides insights to help you achieve your fitness goals and maintain a healthy lifestyle."""
    },
    {
        "id": "4",
        "name": "Noise Cancelling Earbuds",
        "description": """Immerse yourself in sound with our Noise Cancelling Earbuds.
        These in-ear earbuds feature advanced adaptive noise control, reducing background noise for a focused listening experience.
         Designed for comfort and stability, they fit snugly in your ears and stay in place during workouts or commutes.
         The voice assistant integration allows you to manage music, calls, and smart devices hands-free.
         High-fidelity audio delivers crisp highs and deep bass, making every song a rich experience. With long battery life and a portable charging case, you can enjoy music throughout the day without interruption.
         Ideal for busy professionals, travelers, and fitness enthusiasts, these earbuds combine style, technology, and convenience in a compact design that fits perfectly into your lifestyle."""
    },
    {
        "id": "5",
        "name": "Gaming Mouse",
        "description": """Elevate your gaming experience with our high-precision Gaming Mouse. Designed for gamers, it features adjustable DPI settings that allow you to switch sensitivity levels instantly, perfect for fast-paced games requiring quick reflexes.
         The ergonomic design reduces hand fatigue during long gaming sessions, while customizable RGB lighting adds a personal touch to your setup.
         Durable switches ensure millions of clicks for consistent performance.
         The mouse’s high-speed tracking and low-latency connectivity provide smooth, accurate movement, giving you a competitive edge.
         Compatible with both Windows and Mac, it is perfect for casual and professional gamers alike. Whether you’re into RPGs, shooters, or strategy games, this mouse offers precision, comfort, and style in one package."""
    },
    {
        "id": "6",
        "name": "Smart Home Speaker",
        "description": """Transform your living space with our Smart Home Speaker.
         Equipped with a voice-controlled assistant, it allows you to play music, control smart home devices, set reminders, and get real-time information hands-free.
         High-quality audio ensures clear vocals and deep bass, enriching every song, podcast, or audiobook.
         Connect it via Wi-Fi or Bluetooth for seamless integration with your existing devices.
         Compact and stylish, it fits any room decor while offering maximum functionality.
         With multi-room audio support, you can synchronize multiple speakers to fill your home with sound.
         Ideal for smart home enthusiasts, music lovers, and busy households, this speaker brings convenience, entertainment, and smart technology together in one elegant device."""
    }
]

from langchain.docstore.document import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
docs = [Document(page_content=p["description"], metadata={"id": p["id"], "name": p["name"]}) for p in products]
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=20)
split_docs = text_splitter.split_documents(docs)
print(len(split_docs))

from langchain.embeddings import SentenceTransformerEmbeddings

embedded = SentenceTransformerEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

from langchain.vectorstores import Chroma
model = Chroma.from_documents(split_docs,embedded)
query = " product for the fitness enthusiasts"
similar = model.similarity_search(query, k=5)
print(similar)

#persistance
persist_dir = "chromadb"
vectordb = Chroma.from_documents(documents=split_docs,embedding=embedded,persist_directory = persist_dir)
vectordb.persist()

#adding one more item

new_item = {
    "id": "7",
    "name": "Advanced Running Shoes",
    "description": "High-performance running shoes designed for fitness enthusiasts. Lightweight and breathable with excellent cushioning."
}

new_doc =Document(page_content=new_item["description"], metadata={"id":new_item["id"], "name":new_item["name"]})
vectordb.add_documents([new_doc])
vectordb.persist()



