# -*- coding: utf-8 -*-
"""Social Media Trend Grouping .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubSlNxE_-Fzus12w7LqP9bZBusffIcgI

#Social Media Trend Grouping

1. Scenario:You have thousands of tweets about a product launch.
2. Task: Use Sentence Embeddings + KMeans clustering to group tweets discussing similar topics (e.g., “camera quality,” “battery life,” “price”).
"""

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
import numpy as np

tweets = [
    "The new phone's camera quality is stunning!",
    "Battery life lasts more than two days — impressive!",
    "Why is the price so high for this model?",
    "I love the performance speed of this new device.",
    "Charging speed could be better.",
    "Camera takes amazing low-light photos.",
    "Too expensive compared to last year’s version.",
    "The battery drains quickly when gaming.",
    "Great value for the price!",
    "Performance feels super smooth while multitasking."
]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

embeded_twits = model.encode(tweets)

kmeans= KMeans(n_clusters=3, random_state=42)
kmeans.fit(embeded_twits)
labels = kmeans.labels_
num_clusters = 3

for cluster_num in range(num_clusters):
    print(f"\nCluster {cluster_num + 1}:")
    for i, tweet in enumerate(tweets):
        if labels[i] == cluster_num:
            print(f" - {tweet}")